### ISSUE TITLE
Badge alignment is skewed by native subscription/comment icons

### ISSUE THREAD

**Issue by rohanliston** [dwillie/badger#4]
When a card has a comment (speech bubble) or subscription (eye) icon, it becomes more difficult to visually scan down a list of cards. Perhaps it would look better if the native Trello icons were placed on a separate line underneath the badges?

![screenshot from 2016-02-03 14-25-30](https://cloud.githubusercontent.com/assets/1980929/12772129/b3e2e694-ca82-11e5-8c8a-c6272e2f5272.png)

**Comment by dwillie** [comment]
Should be fixed by changes from b39465f67ee3cb19b368295b5227f67c5fba8170
